version: '3.9'

services:
  db:
    image: postgres
    restart: on-failure
    ports:
      - "45432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_TIMEZONE: Asia/Jakarta
      PGDATA: /data/postgres
    networks:
      - net-svc
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db:/data/postgresdocke

  be-numisroad-svc:
    container_name: be-numisroad-svc
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "40001:15001"
    networks:
      - net-svc
    depends_on:
      db:
        condition: service_healthy
    restart: always
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_PORT: 45432

  fe-svc:
    container_name: fe-svc
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "40000:15000"  # Port default untuk Next.js
    networks:
      - net-svc
    depends_on:
      - be-numisroad-svc
    restart: always

networks:
  net-svc:
    name: net-svc
    driver: bridge

volumes:
  db: